const ADD_HISTORY_FROM_STORAGE = "ADD_HISTORY_FROM_STORAGE";
const STORE_HISTORY = "STORE_HISTORY";
const ADD_HISTORY = "ADD_HISTORY";
const DELETE_ALL_HISTORY = "DELETE_ALL_HISTORY";
const ADD_HISTORY_TO_REGEX = "ADD_HISTORY_TO_REGEX";
const STORE_THEME = "STORE_THEME";
const CHANGE_THEME = "CHANGE_THEME";
const FETCH_THEME = "FETCH_THEME";
const SELECT_REGEX_DOCUMENT = "SELECT_REGEX_DOCUMENT";
const SELECT_METHODS_DOCUMENT = "SELECT_METHODS_DOCUMENT";
const SELECT_FLAGS_DOCUMENT = "SELECT_FLAGS_DOCUMENT";
const REMOVE_SELECTED_DOCUMENT = "REMOVE_SELECTED_DOCUMENT";
const STORE_SAVED = "STORE_SAVED";
const ADD_SAVED = "ADD_SAVED";
const DELETE_ALL_SAVED = "DELETE_ALL_SAVED";
const ADD_SAVED_FROM_STORAGE = "ADD_SAVED_FROM_STORAGE";
const ADD_SAVED_TO_REGEX = "ADD_SAVED_TO_REGEX"
const DELETE_SELECTED_SAVED = "DELETE_SELECTED_SAVED"
export {
  ADD_HISTORY_FROM_STORAGE,
  STORE_HISTORY,
  ADD_HISTORY,
  DELETE_ALL_HISTORY,
  ADD_HISTORY_TO_REGEX,
  FETCH_THEME,
  STORE_THEME,
  CHANGE_THEME,
  SELECT_REGEX_DOCUMENT,
  SELECT_METHODS_DOCUMENT,
  SELECT_FLAGS_DOCUMENT,
  REMOVE_SELECTED_DOCUMENT,
  STORE_SAVED,
  ADD_SAVED,
  DELETE_ALL_SAVED,
  ADD_SAVED_FROM_STORAGE,
  ADD_SAVED_TO_REGEX,
  DELETE_SELECTED_SAVED
};
